apiVersion: apps/v1
kind: Deployment
metadata:
  name: citest
  labels:
    app.kubernetes.io/name: citest
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: citest
  template:
    metadata:
      labels:
        app.kubernetes.io/name: citest
    spec:
      containers:
      - name: citest
        image: templain/citest:f70f7ca57ee55fa1ff58905844434bbc332fdea5
        ports:
          - containerPort: 80
