apiVersion: apps/v1
kind: Deployment
metadata:
  name: citest
  labels:
    app.kubernetes.io/name: citest
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: citest
  template:
    metadata:
      labels:
        app.kubernetes.io/name: citest
    spec:
      containers:
      - name: citest
        image: templain/citest:bff485b3634a8acb7346a8659f28ba3653af24d3
        ports:
          - containerPort: 80
