apiVersion: apps/v1
kind: Deployment
metadata:
  name: citest
  labels:
    app.kubernetes.io/name: citest
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: citest
  template:
    metadata:
      labels:
        app.kubernetes.io/name: citest
    spec:
      containers:
      - name: sampleapp
        image: templain/citest:06428ef6368258f9dd4d08d56a67e320551fd3cc
        ports:
          - containerPort: 80
