apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-citest
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifest/citest/overlays/dev
    repoURL: https://github.com/templain/cdtest
    targetRevision: dev
